### ISSUE TITLE
转换代码乱码问题

### ISSUE THREAD

**Issue by yulinfeng16** [yulinfeng16/YLFCY-#7]
在代码转换中会有大概率出现乱码。
你应该暂时不能于0.9.0pre1里面发现这个bug，但是在未来的版本中，如果这个问题不被修复，它将影响代码转换：
fprintf
顺便提一嘴，本项目使用C++开发。

**Comment by djeneu** [comment]
我认为这可能对你有帮助：https://blog.csdn.net/weixin_32795427/article/details/116802866

**Comment by yulinfeng16** [comment]
> 我认为这可能对你有帮助：https://blog.csdn.net/weixin_32795427/article/details/116802866

感谢！

**Comment by yulinfeng16** [comment]
> 我认为这可能对你有帮助：https://blog.csdn.net/weixin_32795427/article/details/116802866
等一下。_ftprintf是什么？我并不是一个编程老手，但我在网上没有找到与之相关的百科。望指教。

**Comment by yulinfeng16** [comment]
刚刚发现了这个：
fprintf_s
不知道行不行？

**Comment by yulinfeng16** [comment]
> 刚刚发现了这个： fprintf_s 不知道行不行？

好吧，不行。在一番搜索后，我发现做这些需要使用VS。但我使用的是Dev-C++,这个函数没有包括在`stdio.h`中。所以，恐怕下个版本发布要花很长时间了。

**Comment by yulinfeng16** [comment]
好消息！我改了一下代码使fprintf不是每次输出单个字符，问题缓解了。
